### PR TITLE
feat(mangrove.js): add permit functionality

### LINKED ISSUE #239: Add functions to enable`permit` and `marketOrderFor` in the API
`permit` function need user to forge a secp256k1 signature. This is required if `marketOrderFor` and `snipeFor` functions are to be used by a delegate taker (such as a bot).
Support for an easy use of `permit` (and by extension `marketOrderFor` would be quite useful for bot makers.

### PR DESCRIPTION
**Pull request by adhusson**
Closes #239

┆Issue is synchronized with this [Monday item](https://mangrovedao.monday.com/boards/3894180513/pulses/3901902378) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by jkrivine — APPROVED** [review]
Top tu pourrais ajouter les tests qui vont avec?

**Comment by adhusson** [comment]
bon d'accord j'accepte

**Comment by peterMangrove** [comment]
@adhusson Can this be merged?

**Comment by adhusson** [comment]
Yes, I don't know why it never was!

**Pull request merged**
